name: Auto Push to Main

on:
  schedule:
    - cron: "0/5 * * * *"

  push:
    branches:
      - develop  
    
jobs:
  merge_to_main:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  
      - name: Fetch Branches
        run: |
          git config --global user.name "Satyajeet256"
          git config --global user.email "snpaygude@gmail.com"
          git fetch origin main
          git fetch origin develop

      - name: Merge Changes
        id: merge
        run: |
          git checkout main
          if git merge --no-ff origin/develop; then
            echo "Merge successful."
          else
            echo "No changes to merge."
            exit 78
          fi

      - name: Add New Files
        if: steps.merge.outcome == 'success'
        run: |
          git config --global user.name "Satyajeet256"
          git config --global user.email "snpaygude@gmail.com"
          git diff --name-only --diff-filter=A origin/develop | xargs -I % git checkout main -- %

      - name: Commit and Push Changes
        if: steps.merge.outcome == 'success'
        run: |
          git config --global user.name "Satyajeet256"
          git config --global user.email "snpaygude@gmail.com"
          git add .
          git commit -m "Merge changes from develop"
          git push origin main
