name: Auto Push to Main

on:
  schedule:
    - cron: "0/5 * * * *"
    
jobs:
  push_to_main:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  
      - name: Add Files
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git checkout main
          git merge develop --no-ff --no-edit
          git add .
          git status   # Optional: Display the status to verify the added files

      - name: Commit and Push
        run: |
          git commit -m "Add new files"
          git push origin main  
   
      
