name: Auto Push to Main

on:
  schedule:
    - cron: "0/5 * * * *"
    
jobs:
  push_to_main:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        env:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  
      - name: Merge Changes
        run: |
          git config --global user.name "Satyajeet256"
          git config --global user.email "snpaygude@gmail.com"
          git checkout main
          git merge develop --no-ff --no-edit
          git push origin main

      - name: Add New Files
        run: |
          git checkout main
          git diff --name-only develop | xargs -I % sh -c 'git checkout develop -- %'

      - name: Commit and Push New Files
        run: |
          git config --global user.name "Satyajeet256"
          git config --global user.email "snpaygude@gmail.com"
          git add .
          git commit -m "Add/update files from develop"
          git push origin main
